package com.hotelreservations.reactivespring.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDate;

//Identifies this class as a domain object to be persistent to MongoDB
@Document
public class Reservation {
    //Denormalized data format
    private Long roomNumber;
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    private LocalDate checkIn;
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    private LocalDate checkOut;
    //Sine we are storing price as whole dollars I used integer otherwise use Big Decimal to make note of cents etc.
    private Integer price;

    //Auto generated hash from MongoDB
    @Id
    private String id;

    public Reservation(){

    }

    public Reservation(Long roomNumber, LocalDate checkIn, LocalDate checkOut, Integer price){
        this.roomNumber = roomNumber;
        this.checkIn = checkIn;
        this.checkOut = checkOut;
        this.price = price;
    }

    public Long getRoomNumber() {
        return roomNumber;
    }

    public LocalDate getCheckIn() {
        return checkIn;
    }

    public LocalDate getCheckOut() {
        return checkOut;
    }

    public Integer getPrice() {
        return price;
    }

    public void setRoomNumber(Long roomNumber) {
        this.roomNumber = roomNumber;
    }

    public void setCheckIn(LocalDate checkIn) {
        this.checkIn = checkIn;
    }

    public void setCheckOut(LocalDate checkOut) {
        this.checkOut = checkOut;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    //Id is autogenerated so you won't have to set it manually
    public String getId() {
        return id;
    }
}
